### PR TITLE
Feature/ci conda

### PR DESCRIPTION
**Pull request by mprorock**
adds a CI file for conda env testing per #4

### CODE REVIEW

**Comment by mprorock** [comment]
stacks on top of #4 and #6 which should be merged first

**Comment by SteveLasker** [comment]
@mprorock, looks like CI is now working, and you just have a small merge conflict.

**Comment by mprorock** [comment]
> @mprorock, looks like CI is now working, and you just have a small merge conflict.

should be resolved now

**Review by SteveLasker — APPROVED** [review]
LGTM

**Comment by SteveLasker** [comment]
Thanks @mprorock, awaiting @letmaik to also confirm...

**Review by letmaik — APPROVED** [review]

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
Who shall merge?

**Comment by SteveLasker** [comment]
@mprorock, looks like your [last commit ](https://github.com/scitt-community/scitt-api-emulator/pull/7/commits/9b856dbddf93e2ed34e77afcf626299f54fa4700 )wasn't signed, blocking the merge gate...

**Comment by letmaik** [comment]
@SteveLasker Can we disable the requirement for commit signing please? This will overly restrict contributions at this point.

**Comment by SteveLasker** [comment]
While it's definitely annoying, it's a common means to assure authors of content are donating it. It also seems kinda weird if we don't support signing, given the work we're doing :)

**Comment by letmaik** [comment]
I think we want to enforce squash merging anyway in the repo settings to avoid accidental pollution of main and reduce manual git work in feature branches. In that case, GitHub signs the squashed commit itself. Many projects do that.

**Pull request merged**
